In [1]:
import pandas as pd
import numpy as np
import json

In [2]:
df = pd.read_csv("E:\iNeuron\iNeuron Projects/AirBNB.csv")

C:\Users\DELL\AppData\Local\Temp\ipykernel_10028\862532252.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("E:\iNeuron\iNeuron Projects/AirBNB.csv")


In [3]:
for column in df.columns:
    if df[column].dtype == "object":
        print(column.upper(), ':', df[column].nunique())
        print()
        print(df[column].value_counts())
        print()

ROOM_TYPE : 3

Entire home/apt    41308
Private room       30635
Shared room         2163
Name: room_type, dtype: int64

CANCELLATION_POLICY : 3

strict      32500
flexible    22543
moderate    19060
Name: cancellation_policy, dtype: int64

CLEANING_FEE : 2

True     54399
False    19708
Name: cleaning_fee, dtype: int64

INSTANT_BOOKABLE : 2

f    54660
t    19451
Name: instant_bookable, dtype: int64



In [4]:
df.isnull().sum()

id                          0
room_type                   5
accommodates                3
bathrooms                 203
cancellation_policy         8
cleaning_fee                4
instant_bookable            0
review_scores_rating    16722
bedrooms                   92
beds                      131
log_price                   0
dtype: int64

In [5]:
df_mean = df.copy()

In [6]:
cat = []
num = []

for i in df_mean.columns:
    if df_mean[i].dtype == 'object':
        cat.append(i)
    else:
        num.append(i)

In [7]:
cat

['room_type', 'cancellation_policy', 'cleaning_fee', 'instant_bookable']

In [8]:
num

['id',
 'accommodates',
 'bathrooms',
 'review_scores_rating',
 'bedrooms',
 'beds',
 'log_price']

In [9]:
df_mean.head(2)

id        room_type  accommodates  bathrooms cancellation_policy  \
0  6901257  Entire home/apt           3.0        1.0              strict   
1  6304928  Entire home/apt           7.0        1.0              strict   

  cleaning_fee instant_bookable  review_scores_rating  bedrooms  beds  \
0         True                f                 100.0       1.0   1.0   
1         True                t                  93.0       3.0   3.0   

   log_price  
0   5.010635  
1   5.129899

### Fill the missing values in the columns by its mean in Numerical Columns

In [10]:
for column in df_mean.columns:
    if df_mean[column].dtype != 'object':
        mean = df_mean[column].mean()
        df_mean[column] = df_mean[column].fillna(mean)

In [11]:
df_mean.isnull().sum()

id                      0
room_type               5
accommodates            0
bathrooms               0
cancellation_policy     8
cleaning_fee            4
instant_bookable        0
review_scores_rating    0
bedrooms                0
beds                    0
log_price               0
dtype: int64

### Fill the missing values in the columns by its mode in categorical Columns

In [12]:
for column in df_mean.columns:
    if df_mean[column].dtype == 'object':
        mode = df_mean[column].mode()[0]  # Extract the first mode value
        df_mean[column] = df_mean[column].fillna(mode)

In [13]:
df_mean.isnull().sum()

id                      0
room_type               0
accommodates            0
bathrooms               0
cancellation_policy     0
cleaning_fee            0
instant_bookable        0
review_scores_rating    0
bedrooms                0
beds                    0
log_price               0
dtype: int64

In [14]:
# Extracting columns with data type 'object' (string-type columns)
object_df = df_mean.select_dtypes(include=['object','bool'])

# Extracting columns with data type 'float' (floating-point columns)
float_df = df_mean.select_dtypes(include=['float'])

In [15]:
object_df.head(2)

room_type cancellation_policy  cleaning_fee instant_bookable
0  Entire home/apt              strict          True                f
1  Entire home/apt              strict          True                t

In [16]:
float_df.head(2)

accommodates  bathrooms  review_scores_rating  bedrooms  beds  log_price
0           3.0        1.0                 100.0       1.0   1.0   5.010635
1           7.0        1.0                  93.0       3.0   3.0   5.129899

In [17]:
df_mean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74111 entries, 0 to 74110
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   id                    74111 non-null  int64  
 1   room_type             74111 non-null  object 
 2   accommodates          74111 non-null  float64
 3   bathrooms             74111 non-null  float64
 4   cancellation_policy   74111 non-null  object 
 5   cleaning_fee          74111 non-null  bool   
 6   instant_bookable      74111 non-null  object 
 7   review_scores_rating  74111 non-null  float64
 8   bedrooms              74111 non-null  float64
 9   beds                  74111 non-null  float64
 10  log_price             74111 non-null  float64
dtypes: bool(1), float64(6), int64(1), object(3)
memory usage: 5.7+ MB


In [18]:
object_df['room_type'].value_counts()

Entire home/apt    41313
Private room       30635
Shared room         2163
Name: room_type, dtype: int64

In [19]:
# Extracting specific columns and creating a new dataset
object_df.head(2)

room_type cancellation_policy  cleaning_fee instant_bookable
0  Entire home/apt              strict          True                f
1  Entire home/apt              strict          True                t

In [20]:
from sklearn.preprocessing import OneHotEncoder

In [21]:
ohe = OneHotEncoder()

In [22]:
ohe.fit_transform(object_df[['room_type','cancellation_policy','cleaning_fee','instant_bookable']])

<74111x10 sparse matrix of type '<class 'numpy.float64'>'
	with 296444 stored elements in Compressed Sparse Row format>

In [23]:
object_df1 = ohe.fit_transform(object_df[['room_type','cancellation_policy','cleaning_fee','instant_bookable']]).toarray()
object_df1

array([[1., 0., 0., ..., 1., 1., 0.],
       [1., 0., 0., ..., 1., 0., 1.],
       [1., 0., 0., ..., 1., 0., 1.],
       ...,
       [1., 0., 0., ..., 1., 0., 1.],
       [1., 0., 0., ..., 1., 0., 1.],
       [1., 0., 0., ..., 0., 1., 0.]])

In [24]:
object_df1.shape

(74111, 10)

In [25]:
object_df2 = pd.DataFrame(object_df1)
object_df2

0    1    2    3    4    5    6    7    8    9
0      1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0
1      1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0
2      1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0
3      1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0
4      1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
74106  0.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0
74107  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0
74108  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0
74109  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0
74110  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0

[74111 rows x 10 columns]

In [26]:
df2 = np.hstack((object_df2,float_df ))

In [27]:
df2

array([[1.        , 0.        , 0.        , ..., 1.        , 1.        ,
        5.01063529],
       [1.        , 0.        , 0.        , ..., 3.        , 3.        ,
        5.12989872],
       [1.        , 0.        , 0.        , ..., 1.        , 3.        ,
        4.97673374],
       ...,
       [1.        , 0.        , 0.        , ..., 2.        , 2.        ,
        5.22035583],
       [1.        , 0.        , 0.        , ..., 0.        , 2.        ,
        5.27299956],
       [1.        , 0.        , 0.        , ..., 1.        , 2.        ,
        4.85203026]])

In [28]:
df3 =  pd.DataFrame(df2)
df3

0    1    2    3    4    5    6    7    8    9    10   11          12  \
0      1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0  3.0  1.0  100.000000   
1      1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  7.0  1.0   93.000000   
2      1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  5.0  1.0   92.000000   
3      1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  4.0  1.0   94.067365   
4      1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  2.0  1.0   40.000000   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...         ...   
74106  0.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  1.0   94.067365   
74107  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0  4.0  2.0   93.000000   
74108  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  5.0  1.0   94.000000   
74109  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  2.0  1.0   94.067365   
74110  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  4.0  1.0   96.000000   

        13   14        15  
0      1.0  1.0  5.010635  
1      3.0  3.0  5.129899  
2      1.0  3.0  4.976734  
3      2.0  2.0  6.620073  
4      0.0  1.0  4.744932  
...    ...  ...       ...  
74106  1.0  1.0  4.605170  
74107  2.0  4.0  5.043425  
74108  2.0  2.0  5.220356  
74109  0.0  2.0  5.273000  
74110  1.0  2.0  4.852030  

[74111 rows x 16 columns]

In [29]:
y=df3.iloc[:,-1:]

In [31]:
X = df3.iloc[:,:-1]

In [32]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [33]:


# Splitting the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Display the shapes of the resulting datasets
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (59288, 15)
X_test shape: (14823, 15)
y_train shape: (59288, 1)
y_test shape: (14823, 1)


In [66]:
from sklearn.preprocessing import StandardScaler

# Create a StandardScaler instance
scaler1 = StandardScaler()

In [67]:
scaler1.fit(X_train)

StandardScaler()

In [68]:
# Transform both training and testing data using the scaler
x_train_scaled = scaler1.transform(X_train)
x_test_scaled = scaler1.transform(X_test)

In [70]:
scaler1.mean_

array([5.56217110e-01, 4.14569559e-01, 2.92133315e-02, 3.04547295e-01,
       2.56578060e-01, 4.38874646e-01, 2.66209014e-01, 7.33790986e-01,
       7.37653488e-01, 2.62346512e-01, 3.15207648e+00, 1.23618800e+00,
       9.40744561e+01, 1.26582104e+00, 1.71285809e+00])

In [71]:
# covert the numpy array into DataFrame
x_train_scaled = pd.DataFrame(x_train_scaled, columns = X_train.columns)
x_test_scaled = pd.DataFrame(x_test_scaled, columns = X_test.columns)

In [72]:
X_train.head(2)

0    1    2    3    4    5    6    7    8    9    10   11    12   13  \
12048  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0  4.0  1.5  97.0  2.0   
48255  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  2.0  1.0  87.0  1.0   

        14  
12048  3.0  
48255  1.0

In [73]:
x_train_scaled.head(2)

0         1         2         3         4         5         6   \
0  0.89323 -0.841513 -0.173472  1.511146 -0.587479 -0.884383  1.660255   
1  0.89323 -0.841513 -0.173472 -0.661749 -0.587479  1.130732 -0.602317   

         7         8         9         10        11        12        13  \
0 -1.660255  0.596364 -0.596364  0.393744  0.453598  0.425879  0.864571   
1  0.602317 -1.676828  1.676828 -0.534981 -0.406101 -1.029848 -0.313032   

         14  
0  1.022929  
1 -0.566529

In [74]:
np.round(x_train_scaled.describe(),1)

0        1        2        3        4        5        6        7   \
count  59288.0  59288.0  59288.0  59288.0  59288.0  59288.0  59288.0  59288.0   
mean       0.0     -0.0     -0.0     -0.0      0.0      0.0      0.0     -0.0   
std        1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0   
min       -1.1     -0.8     -0.2     -0.7     -0.6     -0.9     -0.6     -1.7   
25%       -1.1     -0.8     -0.2     -0.7     -0.6     -0.9     -0.6     -1.7   
50%        0.9     -0.8     -0.2     -0.7     -0.6     -0.9     -0.6      0.6   
75%        0.9      1.2     -0.2      1.5      1.7      1.1      1.7      0.6   
max        0.9      1.2      5.8      1.5      1.7      1.1      1.7      0.6   

            8        9        10       11       12       13       14  
count  59288.0  59288.0  59288.0  59288.0  59288.0  59288.0  59288.0  
mean       0.0     -0.0     -0.0     -0.0     -0.0     -0.0      0.0  
std        1.0      1.0      1.0      1.0      1.0      1.0      1.0  
min       -1.7     -0.6     -1.0     -2.1    -10.8     -1.5     -1.4  
25%       -1.7     -0.6     -0.5     -0.4     -0.2     -0.3     -0.6  
50%        0.6     -0.6     -0.5     -0.4     -0.0     -0.3     -0.6  
75%        0.6      1.7      0.4     -0.4      0.7     -0.3      0.2  
max        0.6      1.7      6.0     11.6      0.9     10.3     12.9

In [75]:
y_train.head()

15
12048  4.499810
48255  3.806662
39959  5.075174
14926  4.442651
776    4.744932

In [77]:
# Create a StandardScaler instance
scaler2 = StandardScaler()

In [78]:
scaler2.fit(y_train)

StandardScaler()

In [79]:
y_train_scaled = scaler2.transform(y_train)
y_test_scaled = scaler2.transform(y_test)

In [80]:
scaler2.mean_

array([4.78053776])

In [81]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [82]:
# Initialize the Linear Regression model
model = LinearRegression()

In [83]:
# Train the model
model.fit(X_train, y_train)

LinearRegression()

In [84]:
# Make predictions on the test data
y_pred = model.predict(X_test)

In [85]:
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [86]:
print("R-squared (R2):", r2)

R-squared (R2): 0.5191412780146576


In [88]:
# Display results
print("Mean Squared Error (MSE):", mse)

Mean Squared Error (MSE): 0.2470295790367205


In [89]:
model.score(X_test, y_pred)

1.0

In [87]:
model.score(X_train, y_train)

0.5167754603125725

In [90]:
model.score(X_test, y_test)

0.5191412780146576