In [1]:
import pandas as pd
import numpy as np
import json

In [2]:
df = pd.read_csv("E:\iNeuron\iNeuron Projects/AirBNB.csv")

C:\Users\DELL\AppData\Local\Temp\ipykernel_740\862532252.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("E:\iNeuron\iNeuron Projects/AirBNB.csv")


In [4]:
df_median  = df.copy()

In [5]:
df_median.head(3)

id        room_type  accommodates  bathrooms cancellation_policy  \
0  6901257  Entire home/apt           3.0        1.0              strict   
1  6304928  Entire home/apt           7.0        1.0              strict   
2  7919400  Entire home/apt           5.0        1.0            moderate   

  cleaning_fee instant_bookable  review_scores_rating  bedrooms  beds  \
0         True                f                 100.0       1.0   1.0   
1         True                t                  93.0       3.0   3.0   
2         True                t                  92.0       1.0   3.0   

   log_price  
0   5.010635  
1   5.129899  
2   4.976734

In [6]:
df_median.isnull().sum()

id                          0
room_type                   5
accommodates                3
bathrooms                 203
cancellation_policy         8
cleaning_fee                4
instant_bookable            0
review_scores_rating    16722
bedrooms                   92
beds                      131
log_price                   0
dtype: int64

In [7]:
df_median = df.drop(columns = ['id'])

In [8]:
df_median.isnull().sum()

room_type                   5
accommodates                3
bathrooms                 203
cancellation_policy         8
cleaning_fee                4
instant_bookable            0
review_scores_rating    16722
bedrooms                   92
beds                      131
log_price                   0
dtype: int64

### Fill the missing values in the columns by its median in Numerical Columns

In [37]:
for column in df_median.columns:
    if df_median[column].dtype != 'object':
        median = df_median[column].median()  # Extract the first median value
        df_median[column] = df_median[column].fillna(median)

### Fill the missing values in the columns by its mode in categorical Columns

In [39]:
for column in df_median.columns:
    if df_median[column].dtype == 'object':
        mode = df_median[column].mode()[0]  # Extract the first mode value
        df_median[column] = df_median[column].fillna(mode)

In [40]:
df_median.isnull().sum()

room_type               0
accommodates            0
bathrooms               0
cancellation_policy     0
cleaning_fee            0
instant_bookable        0
review_scores_rating    0
bedrooms                0
beds                    0
log_price               0
dtype: int64

In [41]:
# Extracting columns with data type 'object' (string-type columns)
object_df = df_median.select_dtypes(include=['object','bool'])

# Extracting columns with data type 'float' (floating-point columns)
float_df = df_median.select_dtypes(include=['float'])

In [42]:
object_df.head(2)

room_type cancellation_policy  cleaning_fee instant_bookable
0  Entire home/apt              strict          True                f
1  Entire home/apt              strict          True                t

In [43]:
float_df.head(2)

accommodates  bathrooms  review_scores_rating  bedrooms  beds  log_price
0           3.0        1.0                 100.0       1.0   1.0   5.010635
1           7.0        1.0                  93.0       3.0   3.0   5.129899

In [44]:
# Extracting specific columns and creating a new dataset
object_df.head(2)

room_type cancellation_policy  cleaning_fee instant_bookable
0  Entire home/apt              strict          True                f
1  Entire home/apt              strict          True                t

In [45]:
from sklearn.preprocessing import OneHotEncoder

In [46]:
ohe = OneHotEncoder()

In [47]:
ohe.fit_transform(object_df[['room_type','cancellation_policy','cleaning_fee','instant_bookable']])

<74111x10 sparse matrix of type '<class 'numpy.float64'>'
	with 296444 stored elements in Compressed Sparse Row format>

In [48]:
object_df1 = ohe.fit_transform(object_df[['room_type','cancellation_policy','cleaning_fee','instant_bookable']]).toarray()
object_df1

array([[1., 0., 0., ..., 1., 1., 0.],
       [1., 0., 0., ..., 1., 0., 1.],
       [1., 0., 0., ..., 1., 0., 1.],
       ...,
       [1., 0., 0., ..., 1., 0., 1.],
       [1., 0., 0., ..., 1., 0., 1.],
       [1., 0., 0., ..., 0., 1., 0.]])

In [49]:
object_df2 = pd.DataFrame(object_df1)
object_df2

0    1    2    3    4    5    6    7    8    9
0      1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0
1      1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0
2      1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0
3      1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0
4      1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
74106  0.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0
74107  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0
74108  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0
74109  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0
74110  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0

[74111 rows x 10 columns]

In [50]:
df2 = np.hstack((object_df2,float_df ))

In [51]:
df2

array([[1.        , 0.        , 0.        , ..., 1.        , 1.        ,
        5.01063529],
       [1.        , 0.        , 0.        , ..., 3.        , 3.        ,
        5.12989872],
       [1.        , 0.        , 0.        , ..., 1.        , 3.        ,
        4.97673374],
       ...,
       [1.        , 0.        , 0.        , ..., 2.        , 2.        ,
        5.22035583],
       [1.        , 0.        , 0.        , ..., 0.        , 2.        ,
        5.27299956],
       [1.        , 0.        , 0.        , ..., 1.        , 2.        ,
        4.85203026]])

In [52]:
df3 =  pd.DataFrame(df2)
df3

0    1    2    3    4    5    6    7    8    9    10   11     12   13  \
0      1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0  3.0  1.0  100.0  1.0   
1      1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  7.0  1.0   93.0  3.0   
2      1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  5.0  1.0   92.0  1.0   
3      1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  4.0  1.0   96.0  2.0   
4      1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  2.0  1.0   40.0  0.0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...  ...   
74106  0.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  1.0   96.0  1.0   
74107  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0  4.0  2.0   93.0  2.0   
74108  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  5.0  1.0   94.0  2.0   
74109  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  2.0  1.0   96.0  0.0   
74110  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  4.0  1.0   96.0  1.0   

        14        15  
0      1.0  5.010635  
1      3.0  5.129899  
2      3.0  4.976734  
3      2.0  6.620073  
4      1.0  4.744932  
...    ...       ...  
74106  1.0  4.605170  
74107  4.0  5.043425  
74108  2.0  5.220356  
74109  2.0  5.273000  
74110  2.0  4.852030  

[74111 rows x 16 columns]

In [53]:
df3.isnull().sum().sum()

0

In [54]:
y=df3.iloc[:,-1:]

In [55]:
X = df3.iloc[:,:-1]

In [56]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [57]:
# Splitting the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Display the shapes of the resulting datasets
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (59288, 15)
X_test shape: (14823, 15)
y_train shape: (59288, 1)
y_test shape: (14823, 1)


In [58]:
X_train.head(2)

0    1    2    3    4    5    6    7    8    9    10   11    12   13  \
12048  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0  4.0  1.5  97.0  2.0   
48255  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  2.0  1.0  87.0  1.0   

        14  
12048  3.0  
48255  1.0

In [59]:
X_train.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
dtype: int64

In [60]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [61]:
# Initialize the Linear Regression model
model = LinearRegression()

In [62]:
# Train the model
model.fit(X_train, y_train)

LinearRegression()

In [63]:
# Make predictions on the test data
y_pred = model.predict(X_test)

In [64]:
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [65]:
print("R-squared (R2):", r2)

R-squared (R2): 0.5205564589489395


In [66]:
model.score(X_train, y_train)

0.5182955890830212

In [97]:
model.score(X_test, y_test)

0.5205564589489395

In [67]:
# Display results
print("Mean Squared Error (MSE):", mse)

Mean Squared Error (MSE): 0.2463025639396186


In [68]:
model.score(X_test, y_pred)

1.0

In [69]:
print("Coefficients:", model.coef_)

Coefficients: [[ 5.91112351e+10  5.91112351e+10  5.91112351e+10 -8.74803899e+08
  -8.74803899e+08 -8.74803899e+08 -2.97322341e+08 -2.97322341e+08
   4.90344282e+08  4.90344282e+08  8.08194890e-02  1.34984096e-01
   7.11500231e-03  1.59376903e-01 -5.20945138e-02]]


In [70]:
print("Intercept:", model.intercept_)

Intercept: [-5.84294531e+10]


In [71]:
# Display the shapes of the resulting datasets
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (59288, 15)
X_test shape: (14823, 15)
y_train shape: (59288, 1)
y_test shape: (14823, 1)


In [72]:
X_train 

0    1    2    3    4    5    6    7    8    9    10   11     12   13  \
12048  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0  4.0  1.5   97.0  2.0   
48255  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  2.0  1.0   87.0  1.0   
39959  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  4.0  1.0   80.0  0.0   
14926  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  2.0  1.0   96.0  1.0   
776    1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0  3.0  1.0   99.0  1.0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...  ...   
37194  0.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0  2.0  1.5  100.0  1.0   
6265   0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0  1.0   90.0  1.0   
54886  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0  5.0  2.0   91.0  2.0   
860    0.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0  2.0  1.0   96.0  1.0   
15795  0.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0  2.0  1.0  100.0  1.0   

        14  
12048  3.0  
48255  1.0  
39959  2.0  
14926  1.0  
776    1.0  
...    ...  
37194  1.0  
6265   1.0  
54886  2.0  
860    1.0  
15795  1.0  

[59288 rows x 15 columns]

In [73]:
from sklearn.preprocessing import StandardScaler

# Create a StandardScaler instance
scaler1 = StandardScaler()

In [74]:
scaler1.fit(X_train)

StandardScaler()

In [75]:
# Transform both training and testing data using the scaler
x_train_scaled = scaler1.transform(X_train)
x_test_scaled = scaler1.transform(X_test)

In [76]:
scaler1.mean_

array([5.56217110e-01, 4.14569559e-01, 2.92133315e-02, 3.04547295e-01,
       2.56578060e-01, 4.38874646e-01, 2.66209014e-01, 7.33790986e-01,
       7.37653488e-01, 2.62346512e-01, 3.15203751e+00, 1.23554514e+00,
       9.45110984e+01, 1.26546687e+00, 1.71161112e+00])

In [77]:
# covert the numpy array into DataFrame
x_train_scaled = pd.DataFrame(x_train_scaled, columns = X_train.columns)
x_test_scaled = pd.DataFrame(x_test_scaled, columns = X_test.columns)

In [78]:
X_train.head(2)

0    1    2    3    4    5    6    7    8    9    10   11    12   13  \
12048  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0  4.0  1.5  97.0  2.0   
48255  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0  2.0  1.0  87.0  1.0   

        14  
12048  3.0  
48255  1.0

In [79]:
x_train_scaled.head(2)

0         1         2         3         4         5         6   \
0  0.89323 -0.841513 -0.173472  1.511146 -0.587479 -0.884383  1.660255   
1  0.89323 -0.841513 -0.173472 -0.661749 -0.587479  1.130732 -0.602317   

         7         8         9         10        11        12        13  \
0 -1.660255  0.596364 -0.596364  0.393760  0.454601  0.359858  0.864932   
1  0.602317 -1.676828  1.676828 -0.534961 -0.404905 -1.085991 -0.312594   

         14  
0  1.023633  
1 -0.565379

In [80]:
y_train.head()

15
12048  4.499810
48255  3.806662
39959  5.075174
14926  4.442651
776    4.744932

In [81]:
# Create a StandardScaler instance
scaler2 = StandardScaler()

In [82]:
scaler2.fit(y_train)

StandardScaler()

In [83]:
y_train_scaled = scaler2.transform(y_train)
y_test_scaled = scaler2.transform(y_test)

In [85]:
scaler2.mean_

array([4.78053776])

In [86]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [87]:
# Initialize the Linear Regression model
model = LinearRegression()

In [88]:
# Train the model
model.fit(X_train, y_train)

LinearRegression()

In [89]:
# Make predictions on the test data
y_pred = model.predict(X_test)

In [90]:
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [91]:
print("R-squared (R2):", r2)

R-squared (R2): 0.5205564589489395


In [93]:
# Display results
print("Mean Squared Error (MSE):", mse)

Mean Squared Error (MSE): 0.2463025639396186


In [94]:
model.score(X_test, y_pred)

1.0

In [92]:
model.score(X_train, y_train)

0.5182955890830212

In [96]:
model.score(X_test, y_test)

0.5205564589489395